config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'

  get '/felhasznalok', to: 'users#index'

  get  '/felhasznalok/uj', to: 'users#new'
  post '/felhasznalok',    to: 'users#create', as: :create_user

  get   '/felhasznalo/:serial/szerkesztes', to: 'users#edit'
  patch '/felhasznalo/:serial',             to: 'users#update', as: :update_user
end

app/models/address.rb
# == Schema Information
#
# Table name: addresses
#
#  id         :bigint           not null, primary key
#  city       :string(255)      not null
#  country    :string(255)      not null
#  serial     :string(36)       not null
#  street     :string(255)      not null
#  zip_code   :string(10)       not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint
#
# Indexes
#
#  index_addresses_on_user_id  (user_id)
#

class Address < ApplicationRecord

  include Serialable

  validates :country,  presence: true, length: { maximum: 255 }
  validates :zip_code, presence: true, length: { maximum: 10 }
  validates :city,     presence: true, length: { maximum: 255 }
  validates :street,   presence: true, length: { maximum: 255 }
  validate :unique_attribute_set

  belongs_to :user, optional: true

  def unique_attribute_set
    if self.class.find_by(
      country:  country,
      zip_code: zip_code,
      city:     city,
      street:   street
    )
      errors.add(:address, 'has to be unique')
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/serialable.rb
module Serialable
  extend ActiveSupport::Concern

  included do
    before_create :set_serial
  end

  def set_serial
    self.serial = SecureRandom.uuid
  end
end

app/models/role.rb
# == Schema Information
#
# Table name: roles
#
#  id         :bigint           not null, primary key
#  __type     :string(10)       not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint
#
# Indexes
#
#  index_roles_on_user_id  (user_id)
#

class Role < ApplicationRecord

  TYPES = [
    'guest',
    'manager',
    'developer'
  ]

  validates :__type, presence: true, inclusion: { in: TYPES }

  belongs_to :user

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :bigint           not null, primary key
#  name       :string(255)      not null
#  serial     :string(36)       not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  manager_id :bigint
#
# Indexes
#
#  index_users_on_manager_id  (manager_id)
#

class User < ApplicationRecord

  include Serialable

  validates :name, presence: true, uniqueness: { case_sensitive: true }, length: { maximum: 255 }
  validates :manager, manager_relations: true, if: -> { manager.present? }

  has_many   :roles,     before_add: :force_unique_roles
  has_many   :addresses, before_add: :limit_addresses
  belongs_to :manager, class_name: 'User', foreign_key: :manager_id, optional: true
  accepts_nested_attributes_for :addresses

  class << self
    def managers
      joins(:roles).where(roles: { __type: 'manager' })
    end

    def non_managers
      where.not(id: User.pluck(:manager_id))
    end
  end

  def manager?
    roles.any? { |role| role.__type == 'manager' }
  end

  def force_unique_roles(role)
    if roles.pluck(:__type).include?(role_type = role.__type)
      raise(ActiveRecord::RecordInvalid.new, "\"#{name}\" user already has \"#{role_type}\" role")
    end
  end

  def limit_addresses(address)
    if addresses.size >= 5
      raise(ActiveRecord::RecordInvalid.new, 'A user can have maximum 5 addresses')
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_managers, only: [:new, :edit]

  def index
    @users        = User.all
    @non_managers = User.non_managers
  end

  def new
    @user = User.new
  end

  def create
    User.create!(normalized_params(create_user_params))
    redirect_to root_url, notice: 'A felhasználó sikeresen létrehozásra került!'
  rescue => error
    redirect_to root_url, alert: "A felhasználó létrehozása sikertelen! \nHibaüzenet: #{error.message}"
  end

  def edit
    @user = User.find_by(serial: params[:serial])
  end

  def update
    if user = User.find_by(serial: params[:serial])
      user.update!(normalized_params(user_params, user))
      redirect_to root_url, notice: 'A felhasználó sikeresen módosításra került!'
    else
      redirect_to root_url, alert: 'Ilyen felhasználó nem szerepel az adatbázisban!'
    end
  rescue => error
    redirect_to root_url, alert: "A felhasználó módosítása sikertelen! \nHibaüzenet: #{error.message}"
  end

  def set_managers
    @managers = User.managers.pluck(:name, :serial).to_h
  end

  private

  def user_params
    params.require(:user).permit(
      :name,
      :serial,
      :manager_serial,
      addresses_attributes: [
        :country,
        :zip_code,
        :city,
        :street
      ]
    )
  end

  def create_user_params
    user_params.except(:serial).permit!
  end

  def normalized_params(strong_params, user=nil)
    user_addresses = user&.addresses
    strong_params[:manager] = User.find_by(serial: strong_params.delete(:manager_serial))
    strong_params[:addresses_attributes]&.reject! do |address|
      address.values.uniq == [''] || user_addresses&.find_by(address)
    end
    strong_params
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title UserManagement
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/users/_form.html.haml
= form_with(model: @user, url: path, local: true) do |f|
  = f.label 'Név:'
  = f.text_field :name
  %p
  = f.label 'Felettes:'
  = select_tag('user[manager_serial]', options_for_select(@managers, @user.manager&.serial), include_blank: '---')
  %p
  - addresses = @user.addresses
  - addresses += [Address.new] unless addresses.size == 5
  - addresses.each_with_index do |address, index|
    %h4 #{index + 1}. CÍM:
    %p
    = f.label 'Ország'
    = f.text_field '[addresses_attributes][][country]',  value: address.country
    %p
    = f.label 'Irányítószám'
    = f.text_field '[addresses_attributes][][zip_code]', value: address.zip_code
    %p
    = f.label 'Város'
    = f.text_field '[addresses_attributes][][city]',     value: address.city
    %p
    = f.label 'Utca'
    = f.text_field '[addresses_attributes][][street]',   value: address.street
    %p
  = submit_tag 'Mentés'
  %p
=button_to('Mégsem', { action: :index }, method: :get )

app/views/users/_table.html.haml
%table{ hidden: true }
  %thead
    %tr
      %td= 'NÉV'
      %td= 'JOGOSULTSÁGOK'
      %td
  %tbody
    - users.each do |user|
      %tr
        %td= user.name
        %td= user.roles.pluck(:__type).join(',')
        %td
          =button_to('Szerkesztés', { action: :edit, serial: user.serial }, method: :get)

app/views/users/edit.html.haml
%h1= "\"#{@user.name}\" felhasználó szerkesztése"
= render partial: 'users/form', locals: { user: @user, path: update_user_path }

app/views/users/index.html.haml
%h1= 'Felhasználók'

%button{ id: :all_users }= 'Összes felhasználó'
= render partial: 'users/table', locals: { users: @users }
%p
%button{ id: :non_managers }= 'Nem felettes felhasználók'
= render partial: 'users/table', locals: { users: @non_managers }
%p
=button_to('Új felhasználó felvitele', { action: :new }, method: :get)

app/views/users/new.html.haml
%h1= 'Új felhasználó felvitele'
= render partial: 'users/form', locals: { user: @user, path: create_user_path }